### ISSUE TITLE
android.hardware.Camera is Depreciated

### ISSUE THREAD

**Issue by robotics3738** [cheer4ftc/OpModeCamera#2]
Following the instructions in the README, android studio started yelling that `android.hardware.Camera` is depreciated. Doing a quick google search it seems that `android.hardware.Camera2` is the new norm. This error appeared when `import android.hardware.Camera;` was added to the **FtcRobotControllerActivity**.

**Comment by cheer4ftc** [comment]
While Camera is deprecated, the code continues to work in spite of the warnings. In fact, Camera is the only class that will work for Android versions earlier than 21, so writing an app that supports older devices still requires its use in spite of it being deprecated.  I suggest that you just ignore the warnings and use it as is.  :)  See the following link for some more details:  

http://stackoverflow.com/questions/27272845/how-to-use-androids-camera-or-camera2-api-to-support-old-and-new-api-versions-w

**Comment by robotics3738** [comment]
Thank you for your help. I was lost because it was not compiling because Android Studio was not cooperating. But I got it to work. Thank you for helping!
