### ISSUE TITLE
RuntimeException-setParameters failed

### ISSUE THREAD

**Issue by nianyush** [cheer4ftc/OpModeCamera#4]
Cannot init the program(both LinearDetectColor and DetectColor). it shows that 
to attempt recovery, please restart the robot
Error: User code threw an uncaught exception
RuntimeExcepetion - setParameters failed
Driver station: Sony Z5
Robot controller: Hongmi

**Comment by cheer4ftc** [comment]
The setParameters method is calling the built in camera setParameters method. This code has only been tested on ZTE Speed phones (as they're the only ones I have). If you're trying to use it on another phone type you may have to modify the parameter setup to accommodate that phone. What type of phone are you using?

**Comment by nianyush** [comment]
@cheer4ftc I have already test XIaomi and Sony. They both give parameter error. And where can I modify this parameter?

**Comment by cheer4ftc** [comment]
setParameters is used in for_camera_opmodes/OpModeCamera and for_camera_opmodes/LinearOpModeCamera. It is primarily used to set the preview window size on the Robot Controller device. You can try to comment these lines out and see if it still works (it may). If it doesn't work after that, you may have to research yourself as I have no access to Xlaomi or Sony devices. In the US, the Xlaomi and Sony phones are not legal for use in FTC.

**Comment by nianyush** [comment]
@cheer4ftc i thought it might be caused by api 23. I am using android 6.0 to run the robotcontroller. However, in that sdk, android.hardware.camera has been deprecated, and is replacced by camera2.

**Comment by cheer4ftc** [comment]
Even on the ZTE phones, camera has been deprecated but still works (and works better than camera2 in some cases). But yes, I'm not running android 6.0/api23 so I couldn't tell you if that's causing a problem.

Definitely just try commenting out the calls to setParameters in those two files and see what happens, as they're primarily for setting the preview window size.

**Comment by nianyush** [comment]
@cheer4ftc It worked!!! Thank you!!! 
  //  camera.setParameters(parameters);

**Comment by cheer4ftc** [comment]
Great! Do you see the preview window on the Robot Controller device? Do you see the red, green, or blue Telemetry message on the Driver Station if you run one of the sample opmodes? Note that the color detected is using the Front facing camera (the selfie camera) in the default settings.

**Comment by nianyush** [comment]
Yeah, I can see the image and the telemetry message. I have found out how to change it to back camera.
